name: 'baseline'
target_column : 'trip_duration'
categorical_column : ['vendor_id', 'store_and_fwd_flag', 'day_of_week', 'hour_of_day', 'month']
numerical_column : ['passenger_count', 'distance']

n_trials: 5

model: sklearn.linear_model.LinearRegression


encoding: True
scaler:
  _target_: sklearn.preprocessing.MinMaxScaler