name: 'tree_baseline'
version: 1
target_column : 'trip_duration'
categorical_column : ['vendor_id', 'store_and_fwd_flag', 'day_of_week', 'hour_of_day', 'month']
numerical_column : ['passenger_count', 'distance']

model:
  _target_: xgboost.XGBRegressor
  lambda: 0.006133522938531546
  alpha: 4.897478509872067
  colsample_bytree: 0.7
  subsample: 1.0
  learning_rate: 0.008
  n_estimators: 3000
  max_depth: 7
  min_child_weight: 209

encoding: False
scaler:
  _target_: sklearn.preprocessing.MinMaxScaler