name: 'xgboost'
version: 1
target_column : 'trip_duration'
categorical_column : ['vendor_id', 'store_and_fwd_flag', 'day_of_week', 'hour_of_day', 'month']
numerical_column : ['passenger_count', 'distance']

model:
  _target_: xgboost.XGBRegressor
  lambda: 0.33021409499906385
  alpha: 0.00140541253048504
  colsample_bytree: 0.6
  subsample: 1.0
  learning_rate: 0.02
  n_estimators: 3000
  max_depth: 5
  min_child_weight: 34

encoding: False
scaler:
  _target_: sklearn.preprocessing.MinMaxScaler