defaults:
  - process: baseline
  - model: baseline
  - model_select: tree

print_config: True
seed: 34 

hydra:
  run:
    dir: outputs/${hydra.job.name}/${model.name}/${model.version}/${now:%Y-%m-%d_%H-%M-%S}